spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: JWT
          uri: http://localhost:8181
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
        - id: Oder
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/**
          filters:
            - AuthenticationFilter
        - id: Product
          uri: http://localhost:8082
          predicates:
            - Path=/api/v2/**
          filters:
            - AuthenticationFilter
